package debug

/* This file data is copied after you compile off the shelf
* /Users/rajuv/vgraju/git/Work/Utils - regular expression for counters
* anything chagne
 */

func autoGeneratedCounterExpr() (string, int) {
	counterExp := `\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+)`
	return counterExp, 32
}

func autoGeneratedStatsExpr() string {
	expr := `\s*([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+)\s*([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+)`
	return expr
}

func autoGeneratedCfgExpr() string {
	expr := `\s*([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+),([\w\s]+):\s*(\d+)`
	return expr
}
