package debug

import (
	"fmt"
	"regexp"
	"strings"
)

func CfgInfoFun(line lineData) {

	server := line.getFileName()
	text := strings.TrimSpace(line.getText())

	cfgHandler(server, text)

	return
}

func cfgHandler(name string, data string) {
	mymap := map[string]string{}

	expression := autoGeneratedCfgExpr()
	re, _ := regexp.Compile(expression)

	sliceString := re.FindStringSubmatch(data)

	if len(sliceString) == 0 {
		Debug("Raju: no expression match ", sliceString)
		return
	}
	for i := 1; i < len(sliceString)-1; i += 2 {
		key := strings.TrimSpace(sliceString[i])
		value := strings.TrimSpace(sliceString[i+1])
		mymap[key] = value
	}

	fmt.Printf("cfg map::%#v\n", mymap)
	processCfgValues(name, mymap)
}
func processCfgValues(name string, mymap map[string]string) {
	var errstr string
	var mystr string
	Debug("Raju: CfgStatsValues:", mymap)

	mymapint := convertMapStringToMapInt(mymap)

	mystr = "hb_state"
	if mymapint[mystr] != 1 {
		errstr = fmt.Sprintf("%s is No heart beat : %d\n",
			mystr, mymapint[mystr])
		writeToDb(MyError{name, errstr})
	}

	mystr = "curr_uptime"
	cmystr := "last_uptime"
	if mymapint[mystr]-mymapint[cmystr] > 90 {
		errstr = fmt.Sprintf("%s Heart beat > 90: %d\n",
			mystr, mymapint[mystr])
		writeToDb(MyError{name, errstr})
	}

}
